[package]
name = "simpledie"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
num = { version = "0.4.3", features = ["num-bigint", "rand", "alloc"] }
once_cell = "1.20.2"
rand = "0.8.5"
thiserror = "2.0.7"
