[package]
name = "simpledie"
version = "0.1.0"
edition = "2021"

[dependencies]
bon = "3.6.3"
itertools = "0.13.0"
num = { version = "0.4.3", features = ["num-bigint", "rand", "alloc"] }
once_cell = "1.20.2"
rand = { version = "0.8.5", features = ["std"] }
slotmap = "1.0.7"
thiserror = "2.0.7"
