[package]
name = "modron"
version = "0.1.0"
edition.workspace = true

[dependencies]
rand.workspace = true
bon.workspace = true

itertools = "0.14.0"
thiserror = "2.0.17"
ahash = { version = "0.8.12", default-features = false, features = ["no-rng", "std"] }

[lints]
workspace = true
